controllers/TripController.php
<?php

namespace app\controllers;

use app\auth\forms\RegistrationForm;
use app\auth\models\User;
use app\auth\repositories\UserRepository;
use app\auth\services\SignUpService;
use app\companion\DriverTrip;
use app\companion\form\AddDriverTripForm;
use app\companion\form\AddPassengerTripForm;
use app\companion\form\SimpleEmailForm;
use app\companion\model\Car;
use app\companion\model\Trip;
use app\companion\PassengerTrip;
use app\companion\repository\TripRepository;
use app\companion\services\DriverTripService;
use app\companion\services\PassengerTripService;
use app\companion\services\TripActivateService;
use app\feedback\MailService;
use app\models\Dialog;
use app\models\DialogHasUser;
use app\models\GeoCountry;
use app\models\GeoRegion;
use app\models\GeoTown;
use app\models\Message;
use app\models\Respond;
use app\repositories\NotFoundException;
use Yii;
use yii\base\Module;
use yii\db\ActiveRecord;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * Class TripController
 * @package app\controllers
 */
class TripController extends Controller
{
    /**
     * Маппинг - шаг/форма для пассажира
     * Важен порядок
     */
    private const PASSENGER_MAPPER = [
        2 => AddPassengerTripForm::class,
        3 => SimpleEmailForm::class,
        4 => RegistrationForm::class,
    ];

    /**
     * Маппинг - шаг/форма для водителя
     * Важен порядок
     */
    private const DRIVER_MAPPER = [
        2 => AddDriverTripForm::class,
        3 => SimpleEmailForm::class,
        4 => RegistrationForm::class,
    ];

    /** @var PassengerTrip */
    private $passengerTrip;
    /** @var DriverTrip */
    private $driverTrip;
    /** @var UserRepository */
    private $userRepository;
    /** @var MailService */
    private $mailService;
    /** @var SignUpService */
    private $signUpService;
    /** @var PassengerTripService */
    private $passengerTripService;
    /** @var DriverTripService */
    private $driverTripService;
    /** @var TripActivateService */
    private $activateService;
    /** @var TripRepository */
    private $tripRepository;

    /**
     * TripController constructor.
     * @param string $id
     * @param Module $module
     * @param PassengerTrip $passengerTrip
     * @param DriverTrip $driverTrip
     * @param UserRepository $userRepository
     * @param MailService $mailService
     * @param SignUpService $signUpService
     * @param PassengerTripService $passengerTripService
     * @param DriverTripService $driverTripService
     * @param TripActivateService $activateService
     * @param TripRepository $tripRepository
     * @param array $config
     */
    public function __construct(
        string $id,
        Module $module,
        PassengerTrip $passengerTrip,
        DriverTrip $driverTrip,
        UserRepository $userRepository,
        MailService $mailService,
        SignUpService $signUpService,
        PassengerTripService $passengerTripService,
        DriverTripService $driverTripService,
        TripActivateService $activateService,
        TripRepository $tripRepository,
        array $config = []
    )
    {
        parent::__construct($id, $module, $config);
        $this->passengerTrip = $passengerTrip;
        $this->driverTrip = $driverTrip;
        $this->userRepository = $userRepository;
        $this->mailService = $mailService;
        $this->signUpService = $signUpService;
        $this->passengerTripService = $passengerTripService;
        $this->driverTripService = $driverTripService;
        $this->activateService = $activateService;
        $this->tripRepository = $tripRepository;
    }

    public function beforeAction($action)
    {
        if ($action->id == 'view') {
            $model = $this->tripRepository->get(Yii::$app->request->get('id'));
            if ($model->status !== Trip::STATUS_ACTIVE && $model->status !== Trip::STATUS_FINISHED) {
                throw new NotFoundHttpException('Поездка не найдена');
            }
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function actionStart()
    {

        return $this->render('start');
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * @param int $step
     * @return string
     */
    public function actionPassenger(int $step)
    {
        if (!isset(self::PASSENGER_MAPPER[$step])) {
            throw new NotFoundException('Такой страницы не существует');
        }

        $class = self::PASSENGER_MAPPER[$step];
        $model = new $class();
        /** @var AddPassengerTripForm $model */
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($this->isLastStepForPassenger($step)) {

                try {
                    /** @var RegistrationForm $model */
                    $user = $this->signUpService->createUser($model);
                    $this->savePassengerTrip($user, Trip::STATUS_INACTIVE);
                    $this->mailService->sendConfirmEmail($user);
                    Yii::$app->session->setFlash('success', 'На адрес ' . $user->email . ' отправлено письмо с инструкцией для подтверждения поездки');
                } catch (\Exception $e) {
                    Yii::$app->session->setFlash('error', $e->getMessage());
                }

                return $this->redirect('/');

            } else {
                // в зависимости от шага добавляем данные
                if (self::PASSENGER_MAPPER[$step] === AddPassengerTripForm::class) {
                    $this->passengerTrip->addTripInfo($model);
                }

                if (self::PASSENGER_MAPPER[$step] === SimpleEmailForm::class) {
                    /** @var SimpleEmailForm $model
                     * Юзер есть и активен
                     * Юзер есть и не активен
                     */
                    if ($this->userRepository->checkByEmail($model->email)) {

                        $user = $this->userRepository->getByEmail($model->email);

                        try {

                            if (!$user->isCanCreateTrip()) {
                                Yii::$app->session->setFlash('error', 'Вы можете создать не более трех поездок в сутки');
                                return $this->redirect('/');
                            }

                            if ($user->isActive()) {
                                $this->savePassengerTrip($user, Trip::STATUS_ACTIVE, true);
                                Yii::$app->user->login($user);
                                return $this->redirect(['/profile/view']);
                            }

                            if (!$user->isActive()) {
                                $this->savePassengerTrip($user, Trip::STATUS_INACTIVE);
                                Yii::$app->session->setFlash('success', 'Поездки успешно созданны, но пока не активны');
                                return $this->redirect('/');
                            }
                        } catch (\Exception $e) {
                            Yii::$app->session->setFlash('error', $e->getMessage());
                            return $this->redirect('/');
                        }
                    }

                    $this->passengerTrip->addTripEmail($model);
                }
                $this->passengerTrip->setStep($step + 1);
                return $this->redirect($this->getNextLinkForPassenger($step));
            }
        } else {
            // Загружаем из модели PassengerTrip
            // в форму, если вдруг пользователь решил уточнить что-то
            $model->load($this->passengerTrip->getTrip(), '');
        }
        return $this->render('passenger-' . $step, [
            'model' => $model,
            'previousLink' => $this->getPreviousLinkForPassenger($step),
        ]);
    }

    /**
     * @param int $step
     * @param null $type
     * @return string|\yii\web\Response
     */
    public function actionDriver(int $step, $type = null)
    {

        /**
         * @var $user User
         */
        if (!isset(self::DRIVER_MAPPER[$step])) {
            throw new NotFoundException('Такой страницы не существует');
        }

        $class = self::DRIVER_MAPPER[$step];
        $model = new $class();
        /** @var AddDriverTripForm $model */
        $post = Yii::$app->request->post();
        if (Yii::$app->user->isGuest) {
            if ($step == 2 && !$type) {
                return $this->render('change-role');
            } elseif ($step == 2 && $type && !Yii::$app->request->isPost) {
                return $this->render('driver-' . $step, [
                    'model' => $model,
                    'previousLink' => $this->getPreviousLinkForDriver($step),
                ]);

            }
        }
        if ($step == 2 && Yii::$app->request->isPost && isset(Yii::$app->request->post('AddDriverTripForm')['MyAuto']) && Yii::$app->request->post('AddDriverTripForm')['MyAuto'] != 0) {
            $car = Car::findOne(Yii::$app->request->post('AddDriverTripForm')['MyAuto']);
            $post['AddDriverTripForm']['carMarkId'] = $car->mark_id;
            $post['AddDriverTripForm']['carModelId'] = $car->model_id;
            $post['AddDriverTripForm']['carYear'] = $car->year;
        }
        if ($model->load($post) && $model->validate()) {
            if ($this->isLastStepForDriver($step)) {
                try {
                    /** @var RegistrationForm $model */
                    $user = $this->signUpService->createUser($model);
                    $this->saveDriverTrip($user, Trip::STATUS_INACTIVE);
                    $this->mailService->sendConfirmEmail($user);
                    Yii::$app->session->setFlash('success', 'На адрес ' . $user->email . ' отправлено письмо с инструкцией для подтверждения поездки');
                } catch (\Exception $e) {

views/trip/change-role.php
<?php

use yii\web\View;
use yii\helpers\Url;

/* @var $this View */

$this->title = 'Новая поездка: шаг 2 из 4';
?>
<div class="row">
    <div class="col-md-6 col-xs-12 col-lg-offset-3 vert-margin40">
        <h1><?= $this->title ?></h1>

        <a href="<?= Url::to(['trip/driver', 'step' => 2, 'type' => \app\auth\models\User::ROLE_USER]) ?>"
           class="btn btn-lg btn-block btn-success select-role-btn">Частное лицо</a>
        <a href="<?= Url::to(['site/register']) ?>"
           class="btn btn-lg btn-block btn-success select-role-btn">Коммерческий перевозчик</a>

    </div>
</div>

views/trip/country.php
<?php

use app\widgets\GeoWidget;
use yii\helpers\Html;

/* @var \yii\web\View $this */
/* @var \app\models\GeoCountry|null $country */

$title = Html::encode($country->name);
$this->title = 'Попутчики ' . $title . ' в совместные поездки на автомобиле';

$this->params['breadcrumbs'][] = $title;

$this->registerMetaTag(['name' => 'description',
    'content' => 'Совместные поездки на автомобиле по ' . $title . ' , найди себе попутчика и сокращай свои расходы на поездки']);

?>

<div class="trips-country">
    <div class="col-md-2 col-sm-2">
        <?= GeoWidget::widget(['model' => $country]); ?>
    </div>
    <div class="col-md-7 col-sm-7">
        <h1><?= $title; ?></h1>

    </div>
</div>

views/trip/driver-2.php
<?php

use app\companion\form\AddDriverTripForm;
use app\companion\model\Car;
use app\models\CarMark;
use app\models\CarModel;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\web\View;

/* @var $this View */
/* @var $form ActiveForm */
/* @var $model AddDriverTripForm */
/* @var $previousLink string */

$this->title = 'Новая поездка: шаг 2 из 4';
$user = Yii::$app->user->identity;
?>
<h1 class="vert-margin40"><?= $this->title ?></h1>

<?php $form = ActiveForm::begin(['id' => 'add-driver-trip-form']); ?>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-9">
        <h2>Места встречи и высадки:</h2>
    </div>

</div>

<?= $this->render('simple-trip', ['model' => $model->simpleTrip, 'form' => $form]) ?>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-9">
        <h2>Количество мест и стоимость:</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <?= $form->field($model, 'tripCapacity')->textInput() ?>

        <?= $form->field($model, 'price')->textInput() ?>
    </div>
    <div class="col-md-4"></div>
</div>

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-9">
        <h2>Информация об автомобиле:</h2>
    </div>
</div>
<div class="row vert-margin10">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <?php

        if ($user && $user->cars) {
            echo '<strong class="vert-margin30 ">Выбрите из ранее добавленных:</strong>';
            echo Html::dropDownList('AddDriverTripForm[MyAuto]', [], ['Выбрать свое авто'] + \yii\helpers\ArrayHelper::map($user->cars, 'id', function (Car $model) {
                    return $model->carMark->name . ' ' . $model->carModel->name . ' (' . $model->year . ')';
                }), ['class' => 'form-control my_auto']);
            echo '<strong class="vert-margin30 ">Или добавьте новую:</strong>';
        }
        ?>
    </div>
    <div class="col-md-4"></div>
</div>
<div class="row vert-margin40 custom_disable">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <?= $form->field($model, 'carMarkId')->dropDownList(CarMark::getDropdownList(), [
            'class' => 'form-control select2',
            'id' => 'car-mark',
            'prompt' => '- Выбрать -',
        ]); ?>

        <?= $form->field($model, 'carModelId')->dropDownList(CarModel::getDropdownList($model->carMarkId), [
            'class' => 'form-control select2',
            'id' => 'car-model',
            'prompt' => '- Выбрать -',
        ]); ?>

        <?= $form->field($model, 'carYear')->dropDownList(Car::getYears(), [
            'class' => 'form-control select2',
            'prompt' => '- Выбрать -',
        ]); ?>

        <div class="form-group">
            <?= Html::a('Назад', $previousLink, ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
            <?= Html::submitButton('Продолжить', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
        </div>
    </div>
    <div class="col-md-4"></div>
</div>


<?php ActiveForm::end(); ?>

views/trip/index.php
<?php

$this->title = 'Совместные поездки на автомобиле';

$this->registerMetaTag(['name' => 'description',
    'content' => 'Объявления о поиске попутчиков на автомобиле по всем городам России и СНГ, а также предложения коммерческих перевозчиков.']);

$this->params['breadcrumbs'][] = [
    'label' => 'Попутчики на автомобиле',
];
?>


<h1>Попутчики на автомобиле</h1>

views/trip/my.php
<?php

use app\assets\Select2Asset;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $searchForm \app\models\SearchForm */

Select2Asset::register($this);

$this->title = 'Мои объявления';
?>

<div class="body-content">
    <h1><?= $this->title ?></h1>
    <div class="row">
        <div class="col-md-8">
            <p>
                <?= \app\widgets\TripWidget::widget([
                    'title' => '',
                    'my' => true
                ]); ?>
            </p>
        </div>
    </div>
</div>

views/trip/passenger-3.php
<?php

use app\companion\form\SimpleEmailForm;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\web\View;

/* @var $this View */
/* @var $form ActiveForm */
/* @var $model SimpleEmailForm */
/* @var $previousLink string */

$this->title = 'Новая поездка: шаг 3 из 4';
?>
<h1><?= $this->title ?></h1>
<?php $form = ActiveForm::begin(['id' => 'add-email-trip-form']); ?>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <p>Пожалуйста укажите ваш Email.</p>
        <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>
        <div class="form-group">
            <?= Html::a('Назад', $previousLink, ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
            <?= Html::submitButton('Продолжить', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
        </div>
    </div>
    <div class="col-md-4"></div>

    <?php ActiveForm::end(); ?>

views/trip/passenger-4.php
<?php

use app\auth\forms\RegistrationForm;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\web\View;

/* @var $this View */
/* @var $form ActiveForm */
/* @var $model RegistrationForm */
/* @var $previousLink string */

$this->title = 'Новая поездка: шаг 4 из 4';
?>
<h1><?= $this->title ?></h1>
<?php $form = ActiveForm::begin(['id' => 'add-passenger-user-form']); ?>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'phone')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <div class="form-group">
            <?= Html::a('Назад', $previousLink, ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
            <?= Html::submitButton('Завершить', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
        </div>
    </div>
    <div class="col-md-4"></div>
    <?php ActiveForm::end(); ?>

views/trip/region.php
<?php

use app\widgets\GeoWidget;
use yii\helpers\Html;

/* @var \yii\web\View $this */
/* @var \app\models\GeoCountry|null $country */
/* @var \app\models\GeoRegion|null $region */

$title = Html::encode($region->name);
$this->title = 'Попутчики на машине ' . $title;

$this->registerMetaTag(['name' => 'description',
    'content' => 'Поиск попутчиков в Совместные поездки на авто по ' . $title . '. Найти попутчика']);

$this->params['breadcrumbs'][] = [
    'label' => Html::encode($country->name),
    'url' => $country->getUrl(),
];

$this->params['breadcrumbs'][] = $title;

?>

<div class="trips-region">
    <div class="col-md-2 col-sm-2">
        <?= GeoWidget::widget(['model' => $region]); ?>
    </div>
    <div class="col-md-7 col-sm-7">
        <h1><?= $title; ?></h1>
    </div>
</div>

views/trip/respond.php
<?php

use app\auth\models\User;
use app\companion\form\SimpleEmailForm;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\web\View;

/* @var $this View */
/* @var $form ActiveForm */
/* @var $model SimpleEmailForm */
/* @var $trip \app\companion\model\Trip */

$this->title = 'Отклик на поездку: ';
?>
<?php $form = ActiveForm::begin(['id' => 'add-email-trip-form']); ?>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <h1><?= $this->title ?></h1>
        <p class="lead">
            <span>Маршрут:</span> <?= $trip->town_from . ' - ' . $trip->town_to ?>

            <br/>
            <span>Когда: </span><?= $trip->trip_time ?>
        </p>
        <?= $form->field(new User(), 'email')->textInput(['autofocus' => true]) ?>
        <div class="form-group">
            <?= Html::a('Назад', '/trip/' . $trip->id, ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
            <?= Html::submitButton('Откликнуться', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
        </div>
    </div>
    <div class="col-md-3"></div>

</div>
<?php ActiveForm::end(); ?>

views/trip/start.php
<?php

use yii\web\View;
use yii\helpers\Url;

/* @var $this View */

$this->title = 'Новая поездка: шаг 1 из 4';
?>
<div class="row">
    <div class="col-md-6 col-xs-12 col-lg-offset-3 vert-margin40">
        <h1><?= $this->title ?></h1>

        <a href="<?= Url::to(['trip/passenger', 'step' => 2]) ?>" class="btn btn-lg btn-block btn-success select-role-btn">Я пассажир, ищу попутную машину</a>
        <a href="<?= Url::to(['trip/driver', 'step' => 2]) ?>" class="btn btn-lg btn-block btn-success select-role-btn">Я водитель, ищу пассажиров</a>

    </div>
</div>

views/trip/text.php
Отклик на поездку<strong> <?= $trip->town_from . ' - ' . $trip->town_to ?>  </strong> от попутчика: <strong> <?= $user->name ?> </strong><br/>
<strong>Комментарий:</strong> <?= $comment ?>

views/trip/view.php
<?php

use yii\helpers\Html;
use app\components\StringHelper;
use app\companion\model\Trip;

/* @var $this yii\web\View */
/* @var $model \app\companion\model\Trip */

$passengerIcon = '<div class="trip-icon" title="Кол-во пассажиров"><i class="fas fa-user"></i></div>';
$carIcon = '<div  class="trip-icon" title="Автомобиль"><i class="fas fa-car"></i></div>';
$clockIcon = '<div class="trip-icon" title="Время выезда"><i class="fas fa-clock"></i></div>';
$rubIcon = '<div class="trip-icon" title="Стоимость поездки"><i class="fas fa-ruble-sign "></i></div>';
$viewsIcon = '<div class="trip-icon" title="Просмотров"><i class="fas fa-eye "></i></div>';

$townFrom = Html::encode($model->town_from);
$townTo = Html::encode($model->town_to);

$this->title = 'Попутчики ' . $townFrom . ' - ' . $townTo . '. На машине ' .
    StringHelper::mb_ucfirst(Yii::$app->formatter->asDate($model->trip_time, 'php:D d M Y H:i')) . '. ';

$this->registerMetaTag(['name' => 'description',
    'content' => "Поиск попутчиков (пассажиров или водителя) на машине по маршруту: $townFrom - $townTo. Отправление:  " . $model->trip_time]);

$this->params['breadcrumbs'][] = [
    'label' => 'Попутчики на автомобиле',
    'url' => ['/trip/index']
];
$this->params['breadcrumbs'][] = $townFrom . ' - ' . $townTo;

$car = $model->car && $model->car->model_id && $model->car->mark_id ? Html::encode($model->car->carMark->name) . '&nbsp;' . Html::encode($model->car->carModel->name) : Html::encode($model->car->manufacturer) . '&nbsp;' . Html::encode($model->car->model);
$userName = Html::encode($model->user->name);

\app\assets\YMapsAsset::register($this);

?>
    <h1 class="vert-margin30"><?= 'Попутчики' . ' ' . $townFrom . ' &rarr; ' . $townTo; ?> </h1>
    <div class="row">
        <div class="col-md-8">
            <?php
            if ($model->status == Trip::STATUS_FINISHED) {
                ?>
                <div class="alert alert-info">Внимание! данная поездка <strong>состоялась</strong>, попробуйте найти
                    другую поездку по этому маршруту
                </div>
                <?php
            }
            ?>
            <div class="row">


                <div class="col-md-3 center-align vert-margin20">
                    <?= Html::a(
                        Html::img($model->user->avatar ? '/img/profile/' . $model->user->avatar : '/img/thumbs/user150.jpg', [
                            'alt' => Html::encode($model->user->name),
                            'class' => 'img-responsive',
                            'style' => 'max-height: 300px',
                        ]), ['/profile/view', 'id' => $model->user->id]
                    ); ?>

                </div>
                <?php
                if ($model->type == Trip::USER_TYPE_PASSENGER && $model->car) {
                    ?>
                    <div class="col-md-5 center-align vert-margin20">
                        <?= Html::a(
                            Html::img($model->car->avatar ? '/img/car/' . $model->car->avatar : '/img/thumbs/no_photo_auto.png', [
                                'alt' => Html::encode($model->user->name),
                                'class' => 'img-responsive car-img-trip',
                                'style' => 'max-height: 120px;',
                            ]), \yii\helpers\Url::to(['/car/' . $model->car->id])
                        ); ?>
                        <p> <?= Html::a($car, ['/car/' . $model->car->id]) . ' (' . $model->car->year . ') г.в.'; ?></p>
                        <?php
                        if ($model->car_id && $model->car->state_number) {
                            ?>
                            <div class="lead">
                                номер <?= $model->car->state_number ?>
                            </div>
                            <?php
                        }
                        ?>
                    </div>
                    <?php
                }
                ?>
                <div class="col-md-4 vert-margin20">
                    <div class="trip-icon"><i class="fas fa-user"></i></div>
                    <strong> <?= Html::a($userName, ['/profile/view', 'id' => $model->user->id]); ?></strong> ищет
                    <?= $model->type === Trip::USER_TYPE_PASSENGER ? 'пассажиров' : 'водителя'; ?>
                    <br/>
                    <div class="trip-icon"><i class="fas fa-calendar"></i></div>
                    <strong>Дата:</strong> <?= StringHelper::mb_ucfirst(Yii::$app->formatter->asDate($model->trip_time, 'php:D d M Y')); ?>
                    <br/>
                    <div class="trip-icon"><i class="fas fa-clock"></i></div>
                    <strong>Время выезда:</strong> <?= Yii::$app->formatter->asTime($model->trip_time, 'php:H:i'); ?>
                    <br/>
                    <strong>
                        <div class="trip-icon"><i class="fas fa-user"></i>
                        </div><?= $model->type === Trip::USER_TYPE_PASSENGER ? 'Свободных мест:' : 'Пассажиров:'; ?>
                    </strong> <?= $model->passengers; ?>
                    <br/>
                    <strong>
                        <?php
                        $display = false;
                        if ($model->price) {
                            ?>
                            <div class="trip-icon"><i class="fas fa-ruble-sign"></i></div>
                            <?php
                            $display = true;
                            echo $model->type === Trip::USER_TYPE_PASSENGER ? 'Цена за место:' : 'Готовы заплатить:';
                        }
                        ?>

                    </strong>
                    <?= $display ? $model->price . ' руб.' : null; ?>
                </div>

            </div>

            <?php if (!empty($model->description)) { ?>
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <h2>Комментарий к поездке</h2>
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <?= $model->description; ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>

            <h2>Маршрут на карте (ориентировочный)</h2>
            <div id="ymap" style="width:100%;height:400px;" class="vert-margin20">
            </div>
            <p><strong>*Маршрут строится автоматически и может отличаться от реального!</strong></p>


        </div>


        <div class="col-md-4">
            <a href="<?= \yii\helpers\Url::to(['/trip/respond', 'id' => $model->id]) ?>"
               class="btn btn-lg btn-block btn-default">Откликнуться</a>
            <button type="button" class="btn btn-lg btn-block btn-default">Создать свою поездку</button>
            <?php
            if ($model->user_id == Yii::$app->user->id) {
                ?>
                <h3>Это ваша поездка и вы можете:</h3>
                <a href="<?= \yii\helpers\Url::to(['/trip/archive', 'id' => $model->id]) ?>"
                   class="btn btn-lg btn-block btn-default">Деактивировать</a>
                <a href="<?= \yii\helpers\Url::to(['/trip/update', 'id' => $model->id]) ?>"
                   class="btn btn-lg btn-block btn-default">Редактировать</a>
                <?php
            }
            ?>

            <h2>Информация о маршруте:</h2>
            <div class="vert-margin30 small">
                <p>
                    Расстояние: км.<br/>
                    Примерное время в пути: ч.м.<br/>
                    При среднем расходе топлива указанного автомобиля
                    количество топлива которое будет использовано: л.<br/>
                    Ориентировочная стоимость топлива: руб.<br/>
                </p>
            </div>
        </div>
    </div>


<?php
$townFrom = $model->town_from;
$townTo = $model->town_to;
$this->registerJs(
    <<<JS

var map;
var townFrom = "$townFrom";
var townTo = "$townTo";

ymaps.ready(initMap);

function initMap()
{
    map = new ymaps.Map('ymap', {
        center: [55.76, 37.64],
        zoom: 10
    }, {
        searchControlProvider: 'yandex#search'
    });
    
    var route = new ymaps.multiRouter.MultiRoute({   
        referencePoints: [
            townFrom,
            townTo
        ]
    }, {
        boundsAutoApply: true
    });
    
    map.geoObjects.add(route);
    
    route.events.once('update', function() {
        route.getActiveRoute().balloon.open();
    });
    
}

JS
);