controllers/RouteController.php
<?php

namespace app\controllers;

use app\auth\models\User;
use app\companion\model\Trip;
use app\feedback\MailService;
use app\models\Dialog;
use app\models\DialogHasUser;
use app\models\GeoTown;
use app\models\Message;
use app\models\MessageSearch;
use app\models\RouteQueryObject;
use app\models\SearchLogTrip;
use app\models\TripSearch;
use yii\base\Module;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;

class RouteController extends Controller
{

    /** @var MailService */
    private $mailService;

    public function __construct(
        string $id,
        Module $module,
        MailService $mailService,
        array $config = []
    )
    {
        parent::__construct($id, $module, $config);
        $this->mailService = $mailService;
    }


    /**
     * Каталог Букв
     * @return string
     * @throws \yii\db\Exception
     */
    public function actionIndex()
    {
        if (\Yii::$app->session->get('typeFind')) {
            \Yii::$app->session->remove('typeFind');
        }
        $letters = RouteQueryObject::getFirstLettersOfTownsFrom();
        $trips = [];

        foreach ($letters as $letter) {
            $trips[$letter] = RouteQueryObject::getRoutesByFirstLetter($letter, 5, 3600);
        }
        return $this->render('index', [
            'letters' => $letters,
            'trips' => $trips,
        ]);
    }

    /**
     * Список поездок по букве пункта отправления
     * @param string $letter
     */
    public function actionRoutes($letter)
    {
        $letter = mb_substr($letter, 0, 1, 'utf-8');
        $trips = RouteQueryObject::getRoutesByFirstLetter($letter, 5000, 0);

        return $this->render('routes', array(
            'trips' => $trips,
            'letter' => $letter,
        ));
    }

    /**
     * Страница конкретного маршрута
     * @param string $cityFrom
     * @param string $cityTo
     * @return string
     * @throws HttpException
     */
    public function actionView($cityFrom = null, $cityTo = null)
    {
        // поиск поездок..

        $type = null;
        if (!$cityFrom && !$cityTo) {
            $post = \Yii::$app->request->post();
            if (isset($post['driver'])) {
                $type = Trip::USER_TYPE_PASSENGER;
            } elseif (isset($post['passenger'])) {
                $type = Trip::USER_TYPE_DRIVER;
            }
            $post = \Yii::$app->request->post('SearchForm');
            $cityFrom = $post['from'];
            $cityTo = $post['to'];
            $from = GeoTown::getById($cityFrom);
            $to = GeoTown::getById($cityTo);
            if (!$from && $to) {
                RouteQueryObject::updateCreateSearchLogByFromTo(null, $cityTo, null, $to->name);
                return $this->redirect([$to->country->alias . '/' . $to->region->alias . '/' . $to->alias]);
            } elseif ($from && !$to) {
                RouteQueryObject::updateCreateSearchLogByFromTo($cityFrom, null, $from->name, null);
                return $this->redirect([$from->country->alias . '/' . $from->region->alias . '/' . $from->alias]);
            } elseif (!$from && !$to) {
                \Yii::$app->session->setFlash('error', 'Заполните поля поиска');
                return $this->redirect(Url::to(['/']));
            } else {
                RouteQueryObject::updateCreateSearchLogByFromTo($cityFrom, $cityTo, $from->name, $to->name);
            }
            \Yii::$app->session->set('typeFind', $type);
            return $this->redirect(Url::to(['route/view', 'cityFrom' => $from->alias, 'cityTo' => $to->alias]));
        } else {
            $from = GeoTown::getByAlias($cityFrom);
            $to = GeoTown::getByAlias($cityTo);
        }
        if (is_null($from) || is_null($to)) {
            throw new HttpException(404, 'Маршрут не найден');
        }
        if (\Yii::$app->session->get('typeFind')) {
            $type = \Yii::$app->session->get('typeFind');
        }
        return $this->render('view', array(
            'from' => $from,
            'to' => $to,
            'type' => $type
        ));

    }
}

views/route/_trip.php
<?php

use app\components\StringHelper;
use yii\helpers\Html;
use app\companion\model\Trip;
use yii\i18n\MessageFormatter;

/* @var \yii\web\View $this */
/* @var \app\companion\model\Trip $model */

$lookingFor = '';

if ($model->type === Trip::USER_TYPE_DRIVER) {
    $title = 'Пассажиры ищут водителя';
    $lookingFor = 'Ищу водителя';
} elseif ($model->type === Trip::USER_TYPE_PASSENGER) {
    $title = 'Водитель ищет пассажиров';
    $lookingFor = 'Ищу пассажира';
}
?>

<div class="trips-list-item well">
    <div class="row">
        <div class="col-md-2">
            <div class="text-center">
                <?= Html::a(
                    Html::img($model->user->avatar ? '/img/profile/' . $model->user->avatar : '/img/thumbs/user.jpg', [
                        'class' => 'user-avatar',
                        'style' => 'max-width:50px',
                        'alt' => Html::encode($model->user ? $model->user->name : 'unknown'),
                    ]), ['/user/', 'id' => $model->user->id]
                ); ?>
                <div class="looking-for">
                    <?= $lookingFor; ?>
                </div>
            </div>
        </div>
        <div class="col-md-10">
            <div class="trip-header">
                <div class="trip-date pull-left">
                    <?= StringHelper::mb_ucfirst(Yii::$app->formatter->asDate($model->trip_time, 'php:D d M Y')); ?>
                </div>
                <div class="trip-title pull-right">
                    <?= Html::a(Html::encode($model->town_from) . '&nbsp;&rarr;&nbsp;' .  Html::encode($model->town_to), ['/trip/view', 'id' => $model->id]); ?>
                </div>
                <div class="clr"></div>
            </div>
            <div class="tip-content">
                <?= \app\widgets\TripIconsWidget::widget([
                    'model' => $model,
                ]); ?>
                <div class="panel panel-default trip-description">
                    <div class="panel-body">
                        <?= empty($model->description) ? 'Нет описания' : Html::encode($model->description); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/route/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var array $letters
 * @var array $trips
 */
$this->title = "Все марштуры - поиск попутчкиков на автомобиле";

$this->registerMetaTag(['name' => 'description',
    'content' => 'Всем маршруты по которым люди ищут себе попутчиков, выберите тот который вам нужен.']);

$this->params['breadcrumbs'][] = [
    'label' => 'Попутчики по маршруту'
];
?>

<h1>Маршруты</h1>

<?php
foreach ($letters as $key => $letter) {
    if ($key % 3 == 0): ?>
        <div class="row">
    <?php endif; ?>
    <div class="col-sm-4 vert-margin20">
        <?php if (isset($trips[$letter])): ?>
            <p>
                <?php foreach ($trips[$letter] as $trip): ?>
                    <?php echo Html::a($trip['from_name'] . ' - ' . $trip['to_name'], Url::to([
                        'route/view',
                        'cityFrom' => $trip['from_alias'],
                        'cityTo' => $trip['to_alias']
                    ])); ?>
                    <br/>
                <?php endforeach; ?>
            </p>
        <?php endif; ?>

        <strong>
            <?= Html::a(
                "Все маршруты на " . $letter,
                Url::to(['route/routes', 'letter' => $letter])
            ) ?>
        </strong>
    </div>
    <?php if ($key % 3 == 2): ?>
        </div>
    <?php endif; ?>
    <?php
}
?>

<?php if ($key % 3 != 2): ?>
    </div>
<?php endif; ?>

views/route/routes.php
<?php
/**
 * @var $trips \app\models\SearchLogTrip[]
 */
$this->title = "Маршруты на букву " . $letter . " поиск попутчкиков на автомобиле";
$this->registerMetaTag(['name' => 'description',
    'content' => "Все маршруты города отправлния которых начинаются на букву $letter  - попутчкиков на автомобиле"]);

$this->params['breadcrumbs'][] = [
    'label' => 'Попутчики по маршруту',
    'url' => ['/route/']
];
$this->params['breadcrumbs'][] = 'Маршруты на букву ' . $letter;
?>

<h1>Все маршруты на букву "<?php echo $letter; ?>"</h1>

<?php
foreach ($trips as $key => $trip) {
    if ($key % 3 == 0): ?>
        <div class="row">
    <?php endif; ?>
    <div class="col-sm-4">
        <?= \yii\helpers\Html::a(
            $trip['from_name'] . ' - ' . $trip['to_name'],
            \yii\helpers\Url::to(['/route/view', 'cityFrom' => $trip['from_alias'], 'cityTo' => $trip['to_alias']])
        ) ?>
    </div>
    <?php if ($key % 3 == 2): ?>
        </div>
    <?php endif; ?>
    <?php
}
?>
<?php if ($key % 3 != 2): ?>
    </div>
<?php endif; ?>

views/route/view.php
<?php
use yii\helpers\Html;

/**
 * @var \app\models\GeoTown $from
 * @var \app\models\GeoTown $to
 */
$this->title = "Попутчики из " . $from->name . ' в ' . $to->name . " на автомобиле";

$this->registerMetaTag(['name' => 'description',
    'content' => "Все попутчики по маршруту с отправлением из " . $from->name . ' и прибытием в ' . $to->name . " на автомобиле"]);

$this->params['breadcrumbs'][] = [
    'label' => 'Попутчики по маршруту',
    'url' => ['/route/']
];
$this->params['breadcrumbs'][] = $from->name . ' - ' . $to->name;

?>
<div class="row">
    <div class="col-md-8">
        <h1>Попутчики <?php echo $from->name . ' &rarr; ' . $to->name; ?></h1>
    </div>
    <div class="col-md-4">
        <?= Html::a('Создать поездку по этому маршруту', ['/trip/start'], ['class' => 'btn btn-default btn-lg btn-block',]); ?>
    </div>

</div>
<div class="row">
    <div class="col-sm-6">
        <h2 class="vert-margin40">Объявления попутчиков:</h2>

        <ul class="nav nav-tabs">
            <li class="in nav nav-tabs active"><a href="#search-pass" data-toggle="tab"><i aria-hidden="true"></i>Ищут
                    пасажиров</a></li>
            <li class="in nav nav-tabs"><a href="#search-auto" data-toggle="tab"><i aria-hidden="true"></i>Ищут
                    водителей</a>
            </li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane active" id="search-pass">
                <h3>Водители ищут пассажиров</h3>
                <?= \app\widgets\TripSearchWidget::widget([
                    'type' => $type
                ]); ?>
            </div>
            <div class="tab-pane active" id="search-auto">
                <h3>Пассажиры ищут водителей</h3>
                <?= \app\widgets\TripSearchWidget::widget([
                    'type' => $type
                ]); ?>
            </div>
        </div>

    </div>
    <div class="col-sm-6">
        <h2 class="vert-margin40">Предложения коммерческих перевозчиков:</h2>
        <div class="alert alert-info lead">
            Если вы, занимаетесь коммерческими пасажирскими перевозками и вы хотите разместить тут информацию о своих
            маршутах, то вам <a href="#">сюда</a>
        </div>
    </div>
</div>