controllers/SiteController.php
<?php

namespace app\controllers;

use app\auth\services\UserTripsManageService;
use app\feedback\MailService;
use app\models\ContactForm;
use app\models\GeoTown;
use app\auth\forms\LoginForm;
use app\auth\forms\RegistrationForm;
use app\auth\forms\RestorePasswordForm;
use app\models\Message;
use app\models\SearchForm;
use app\auth\models\User;
use app\models\Transaction;
use Yii;
use yii\base\Exception;
use yii\base\Module;
use yii\captcha\CaptchaAction;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\ErrorAction;
use yii\web\HttpException;
use yii\web\Response;

/**
 * Class SiteController
 * @package app\controllers
 */
class SiteController extends Controller
{

    /** @var MailService */
    private $mailService;

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['balance-add-request'],
                        'allow' => true,
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                    'town' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => ErrorAction::class,
            ],
            'captcha' => [
                'class' => CaptchaAction::class,
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function __construct(
        string $id,
        Module $module,
        MailService $mailService,
        array $config = []
    )
    {
        parent::__construct($id, $module, $config);
        $this->mailService = $mailService;
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * @return array
     */
    public function actionTown()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        return GeoTown::findByTerm(Yii::$app->request->post('query'));
    }

    /**
     * @return array
     */
    public function actionTownRegionCountry()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        return GeoTown::findByTermTownRegionCountry(Yii::$app->request->post('query'));
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            if (Yii::$app->getUser()->getIdentity()->role == User::ROLE_ADMIN) {
                return $this->redirect(['/admin/']);
            }
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * @return string
     * @throws Exception
     */
    public function actionRestorePassword()
    {
        $model = new RestorePasswordForm();

        if ($model->load(Yii::$app->request->post()) && $model->resetPassword() && $model->sendLetter()) {
            return $this->render('restore-letter-sent');
        }

        return $this->render('restore-password', [
            'model' => $model,
        ]);
    }

    /**
     * @return string
     * @throws Exception
     */
    public function actionRegister()
    {
        $model = new RegistrationForm();
        if ($model->load(Yii::$app->request->post())) {
            $model->setScenario(User::ROLE_USER);
            if ($model->role == User::ROLE_CARRIER) {
                $model->setScenario(User::ROLE_CARRIER);
            }
            $user = $model->addAttributes();
            if ($model->validate() && $user->save(false)) {
                $this->mailService->sendConfirmEmail($user);
                Yii::$app->session->setFlash('success', 'На адрес ' . $user->email . ' отправлено письмо с инструкцией для подтверждения регистрации');
                return $this->redirect(['/site/index']);
            } else {
                VarDumper::dump(Yii::$app->request->post(), 11, 1);
                VarDumper::dump($model->getErrors(), 11, 1);
            }
        }

        return $this->render('register', [
            'model' => $model,
        ]);
    }

    /**
     * @param string $email
     * @param string $code
     * @return Response
     */
    public function actionConfirm($email, $code)
    {
        $user = User::findOne([
            'email' => $email,
            'confirm_code' => $code,
            'status' => User::STATUS_INACTIVE
        ]);

        if ($user === null) {
            Yii::$app->session->setFlash('error', 'Пользователь с такими данными не найден, либо не требует активации');
            return $this->redirect(['index']);
        }

        if (UserTripsManageService::confirm($user)) {
            Yii::$app->session->setFlash('success', 'Ваш аккаунт активирован');
            Yii::$app->user->login($user);
            return $this->redirect(['/profile/view']);
        }

        Yii::$app->session->setFlash('error', 'Возникла непредвиденная ошибка. Обратитесь в службу поддержки');
        return $this->redirect(['index']);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionFeedback()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('feedback', [
            'model' => $model,
        ]);
    }

    /**
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * @return string
     */
    public function actionSafety()
    {
        return $this->render('safety');
    }

    /**
     * @return string
     */
    public function actionRules()
    {
        return $this->render('rules');
    }

    /**
     * @return string
     */
    public function actionPartners()
    {
        return $this->render('partners');
    }

    public function actionOffer()
    {
        return $this->render('offer');
    }


    /**
     * На этот адрес будут приходить запросы от Яндекса о пополнении кошелька
     * https://povm.ru/user/balanceAddRequest
     */
    public function actionBalanceAddRequest()
    {

        Yii::info('Пришел запрос от Яндекса с уведомлением о пополнении баланса', 'info');
        Yii::info('POST запрос: ' . print_r($_POST, true), 'info');
        $request = Yii::$app->request;

        // разбираем данные, которые пришли от Яндекса
        $amount = $request->post('withdraw_amount') * 100;
        $userId = $request->post('label');
        $hash = $request->post('sha1_hash');

        $secret = Yii::$app->params['yandexMoneySecret'];

        $requestString = $request->post('notification_type') . '&' .
            $request->post('operation_id') . '&' .
            $request->post('amount') . '&' .
            $request->post('currency') . '&' .
            $request->post('datetime') . '&' .
            $request->post('sender') . '&' .
            $request->post('codepro') . '&' .
            $secret . '&' .
            $request->post('label');

        Yii::info('Собранная строка для проверки: ' . $requestString, 'info');

        $requestString = sha1($requestString);

        Yii::info('Зашифрованная строка для проверки: ' . $requestString, 'info');

        if ($requestString == $hash) {
            // данные от яндекса не подделаны, можно зачислять бабло

            $user = User::findOne($userId);

            if ($user instanceof User) {

                Yii::info('Пополняем баланс пользователя: ' . $user->name, 'info');
                $user->balance += $amount;
                $transaction = new Transaction();
                $transaction->user_id = $user->id;
                $transaction->amount = $amount;
                $transaction->description = 'Пополнение баланса пользователя';


                if ($transaction->save() && $user->save()) {
                    Yii::info('Транзакция сохранена, id: ' . $transaction->id, 'info');
                } else {
                    Yii::error('Ошибка при пополнении баланса пользователя ' . $user->id . ' (' . $amount . ' руб.)', 'error');
                    throw new HttpException(500, 'Не удалось пополнить баланс пользователя');
                }

                Yii::info('Пришло бабло от пользователя ' . $user->id . ' (' . $amount . ' руб.)', 'info');
            }
        }
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$title = 'О сайте';
$this->title = $title . ' - ' . Yii::$app->name;
$this->params['breadcrumbs'][] = $title;

$this->registerMetaTag(['name' => 'description',
    'content' => 'Информаци о нашем проекте, кто его сделал, для кого он, для каких целей и т.д.']);

?>
<div class="site-about">
    <h1>Поиск попутчиков &laquo;Поехали вместе&raquo;</h1>
    <div class="row">
        <div class="col-md-8 col-sm-8">
            <p>
                Этот сервис создан для тех людей, которые часто ездят из одного города в другой,
                как в роли пассажира на общественном транспорте, так и для водителей, которые передвигаются на личном авто.
                <br /><br />
                Последним этот сервис поможет сократить расходы на дорогу, взяв с собой попутчика, ведь разделив сумму на двоих
                (или троих), кошелек не так сильно страдает ;) Ну а пассажиром лучше ехать в комфортабельном автомобиле, чем в душном поезде
                или, того хуже, автобусе на узких сидениях и сами знаете с чем еще
            </p>
        </div>
        <div class="col-md-4 col-sm-4">

        </div>
    </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/feedback.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$title = 'Обратная связь';
$this->title = $title . ' - ' . Yii::$app->name;
$this->params['breadcrumbs'][] = $title;

$this->registerMetaTag(['name' => 'description',
    'content' => 'Обратная связь с администрацией проекта. Если у вас есть вопросы и предложения по работе данного сервиса то пожалуйста заполните эту форму.']);
?>
<div class="site-contact">
    <h1><?= Html::encode($title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Спасибо! ваше сообщение отправлено. Мы его уже получили и рассмотрим в ближайшее время.
        </div>

    <?php else: ?>

        <p>
            Если у вас есть вопросы и предложения по работе данного сервиса то пожалуйста заполните эту форму.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/index.php
<?php

use app\assets\Select2Asset;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $searchForm \app\models\SearchForm */

Select2Asset::register($this);

$this->title = 'Попутчики.РУ - Совместные поездки на машине. Поиск попутчиков.';

$this->registerMetaTag(['name' => 'description',
    'content' => 'Попутчики.ру - поиск попутчиков для совместных поездок на автомобиле. Найдите с кем доехать на машине, знакомьтесь. Онлайн сервис - Поехали Вместе!']);

?>

<div class="body-content">

    <div class="row">
        <div class="col-md-8 col-sm-8">
            <h1 class="vert-margin30">Попутчики.Ру - поиск попутчиков</h1>
            <!-- форма поиска -->
            <?= \app\widgets\SearchWidget::widget(); ?>
            <!-- конец формы поиска -->
            <p>
                <?= \app\widgets\TripWidget::widget([
                    'title' => 'Ближайшие поездки',
                ]); ?>
            </p>

        </div>
        <div class="col-md-4 col-sm-4 hidden-xs">
            <?= Html::a('Найти попутчика', ['/trip/start'], [
                'class' => 'btn btn-success btn-lg btn-block',
            ]); ?>
            <h2>Как найти попутчиков?</h2>
            <strong>Сделать это можно двумя способами:</strong> <br/><br/>
            <p><strong>Первый</strong> - воспользоваться формой поиска указав пункты отправления и прибытия,
                найти объявления о поиске попутчиков по вашему маршруту связаться с автором и договориться о месте
                встречи. Если вы не нашли нужную поездку, переходите ко второму способу.
                <br/> <br/>
                <strong>Второй</strong> - создать свое объявление о поиске попутчиков указав пункты "А" и "Б" с крайней
                датой отправления и ждать когда ваши попутчики свяжуться с вами.
            </p>
            <h3>Водителям</h3>
            <p>Указывайте количество свободного места в багажнике и количестве пассажиров которое вы берете, можно ли
                например взять с собой собаку будет ли для неё сбободное место и т.д. чем больше вы укажите
                дополнительной информации тем
                лучше. </p>
            <h3>Пассажирам</h3>
            <p>При создании поездки указывайте максимально полную информацию о количестве, характере и размере багажа,
                количестве человек и иную информацию, которая сможет водителю более подробно понять сможет ли он
                обеспечить вам конфортную поездку</p>
            <h3>Как поехать попутчиком на машине максимально безопасно?</h3>
            <p>Как выбрать попутчика чтобы доехать на машине "от" и "до"?</p>
            <p>Рассказываем:</p>
            <ol>
                <li>Выбирайте поездки с водителями аккаунты который заполнены максимально полно</li>
                <li>Смотрте историю поездок водителя</li>
                <li>Не ездите один, особенно если вы девушка</li>
                <li>Когда будете договариваться о месте встречи спросите сколько всего пасссажиров, чем больше людей тем
                    безопаснее
                </li>
            </ol>
            <h2 class="vert-margin30">Поделиться с друзьями</h2>
            <!--<script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
            <script src="//yastatic.net/share2/share.js"></script>-->
            <div class="ya-share2"
                 data-services="collections,vkontakte,facebook,odnoklassniki,twitter,lj,viber,whatsapp,telegram"></div>
            <h2 class="vert-margin30">Мы в Vk</h2>
            <div id="vk_groups"></div>
            <!--<script type="text/javascript">
                VK.Widgets.Group("vk_groups", {mode: 0, width: "290", height: "290"}, 42392510);
            </script>-->

        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12">


            <h2>Найди попутчиков или попутную машину свою поездку!</h2>

            <p>
                Любите ли Вы природу так, как любим ее мы? Уверены, что да! Мы предлагаем реально действующую схему -
                ездим вместе и уменьшаем вредные выбросы в атмосферу. Только представьте - среднестатистическая
                легковушка выбрасывает за час в атмосферу столько углекислого газа, сколько способно надышать 100
                человек при сильной физической активности! Меньше машин на дороге - больше свежего воздуха. Поборемся за
                чистоту нашей планеты вместе!
            </p>
        </div>
    </div>

    <div class="row">

        <div class="col-md-4 col-sm-4">
            <h3>В некоторых городах слабо развит транспорт</h3>
            <p>Например, поезда ходят пару раз в неделю, а ехать в жарком и тесном автобусе очень некомфортно. С помощью
                нашего сервиса легко найти попутчика который едет на своем авто и поехать с ним</p>
        </div>
        <div class="col-md-4 col-sm-4">
            <h3>Водители ездят далеко в одиночку</h3>
            <p>Ехать одному несколько часов подряд скучно, даже с любимой музыкой. К тому же, удобнее было бы разделить
                расходы на горючее с пассажиром. Поиск попутчика в данном случае решает эту задачу.</p>
        </div>
        <div class="col-md-4 col-sm-4">
            <h3>Людям без машин приходится ездить поездами и автобусами</h3>
            <p>А в машине с кондиционером ехать комфортнее. Не все могут позволить себе автомобиль, но заплатить
                несколько сотен рублей за поездку могут многие.</p>
        </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\auth\forms\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$title = 'Вход';

$this->title = Yii::$app->name . ' - ' . $title;
$this->params['breadcrumbs'][] = $title;
?>
<div class="site-login">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <h1><?= Html::encode($title) ?></h1>
            <?php $form = ActiveForm::begin([
                'id' => 'login-form',
            ]); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Войти', ['class' => 'btn btn-lg btn-primary', 'name' => 'login-button']) ?>
                </div>

                <?= Html::a('Регистрация', ['/site/register']); ?>
                |
                <?= Html::a('Забыли пароль?', ['/site/restore-password']); ?>

            <?php ActiveForm::end(); ?>
        </div>
        <div class="col-md-4"></div>

    </div>
</div>

views/site/offer.php
<?php
$title = 'Пользовательское соглашение';
$this->title = $title . ' - ' . Yii::$app->name;

$this->params['breadcrumbs'][] = $title;
$this->registerMetaTag(['name' => 'description',
    'content' => 'Пользовательское соглашение проекта Поехали Вместе.']);
?>

<h1>Пользовательское соглашение</h1>

views/site/partners.php
<?php

/* @var \yii\web\View $this */

$title = 'Наши партнеры';
$this->title = $title;

$this->params['breadcrumbs'][] = $title;
$this->registerMetaTag(['name' => 'description',
    'content' => 'Партнеры проекта Поехали Вместе.']);
?>

<h1>Наши партнеры</h1>

views/site/register.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use \yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model \app\auth\forms\RegistrationForm */

$this->title = 'Регистрация';

$this->params['breadcrumbs'][] = $this->title;
?>
<div class="auto-form">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <h1><?= Html::encode($this->title); ?></h1>

            <?php
            $form = ActiveForm::begin([
                'fieldConfig' => [
                    'options' => ['class' => 'form_group clearfix'],
                    'enableClientValidation' => false,
                    'template' => "{label}\n<div class=\"col_right\">{input}\n<div class=\"error\">{error}</div></div>",
                ],
            ]) ?>
            <?php
            //            \yii\helpers\VarDumper::dump(Yii::$app->request->referrer,11,1)
            if (stristr(Yii::$app->request->referrer, 'trip/driver')) {
                echo $form->field($model, 'role')->hiddenInput(['value' => 'carrier'])->label(false);
            } else {
                echo $form->field($model, 'role')->dropDownList(\app\auth\models\User::$roles, ['class' => 'roles form-control'])->label('Кто вы?');
            }
            ?>


            <div class="carrier_fields"
                 style="display: <?= $model->role == 'carrier' || stristr(Yii::$app->request->referrer, 'trip/driver') ? 'block' : 'none' ?>">
                <?= $form->field($model, 'name_carrier')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'carrier_count_car')->textInput(['autofocus' => true]) ?>

            </div>
            <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'email')->textInput() ?>

            <?= $form->field($model, 'town_id')->dropDownList([], [
                //  'prompt' => $user->getAttributeLabel('town_id'),
                'class' => 'form-control select-town',
                'data' => [
                    'ajax--url' => Url::to(['/site/town'], true),
                ],
                'pluginOptions' => [
                    'autoclose' => true,
                ]
            ])->label('Город проживания' . ($user->town_id ? ': ' . $user->getTownName() : null)) ?>

            <?= $form->field($model, 'phone')->widget(\yii\widgets\MaskedInput::class, [
                'mask' => '+7 999 999 99 99',
            ]) ?>

            <?= $form->field($model, 'phone_access')->dropDownList($model->phoneAccess())->label('Кому виден ваш телефон') ?>

            <?= $form->field($model, 'password')->passwordInput() ?>


            <div class="form-group">
                <?= Html::submitButton('Зарегистрироваться', ['class' => 'btn btn-block btn-lg btn-primary']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>

views/site/restore-letter-sent.php
<?php

/* @var $this \yii\web\View */

?>

<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <p class="lead">Новый пароль отправлен на e-mail</p>
    </div>
    <div class="col-md-4"></div>
</div>

views/site/restore-password.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model \app\auth\forms\RestorePasswordForm */

$title = 'Восстановление пароля';

$this->title = Yii::$app->name . ' - ' . $title;
$this->params['breadcrumbs'][] = $title;
?>
<div class="restore-password">
    <h1><?= Html::encode($title) ?></h1>

    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <?php $form = ActiveForm::begin([
                'id' => 'restore-password-form',
            ]); ?>

            <?= $form->field($model, 'email')->textInput(['autofocus' => true]); ?>

            <div class="form-group">
                <?= Html::submitButton('Восстановить пароль', ['class' => 'btn btn-primary', 'name' => 'restore-password-button']); ?>
            </div>

            <?= Html::a('Регистрация', ['/site/register']); ?>
            |
            <?= Html::a('Вход', ['/site/login']); ?>

            <?php ActiveForm::end(); ?>
        </div>
        <div class="col-md-4"></div>

    </div>
</div>

views/site/rules.php
<?php

/* @var \yii\web\View $this */

$title = 'Правила сайта';
$this->title = $title . ' - ' . Yii::$app->name;

$this->params['breadcrumbs'][] = $title;
$this->registerMetaTag(['name' => 'description',
    'content' => 'Правила пользования сервисом «Поехали вместе» Пожалуйста придерживайтесь этих правил.']);
?>

<div class="site-rules">
    <h1>Правила пользования сервисом «Поехали вместе»</h1>
    <div class="row">
        <div class="col-md-8 col-sm-8">
            <h2>1. Общие положения</h2>
            <p>
                Водитель — водитель, берущий попутчиков, чтобы скрасить поездку или сократить расходы на поездку.
                <br />
                Пассажир – человек который ищет водителя для совершения поездки с ним по определенному маршруту
                <br /><br />
                1.1. Незнание или не прочтение Правил не освобождает от ответственности.
                <br />
                1.2. Если вы не нашли свое объявление, то оно могло быть удалено из-за нарушения. Не пытайтесь разместить новое, сначала разберитесь, что вы сделали не так.
                <br />
                1.3. Откровенно коммерческие предложения будут оставаться или удаляться по усмотрению Модератора.
            </p>

            <h2>2. Требования и ограничения.</h2>
            <p>
                2.1. Один Перевозчик — один аккаунт. Разные водители, разные транспортные средства — один аккаунт. Все объявления с других аккаунтов будут удаляться, зарегистрированные вновь блокироваться, основной подвергаться наказанию,
                Размещать «по просьбе» разрешено только Водителям и только с указанием ника основного Водителя.
                <br />
                2.2. Объявление должно содержать: <br />
                дату, направление, время выезда, тип транспорта, цену, количество пассажиров, контакты. Рекомендуется маршрут движения, место встречи с попутчиками и т.п.
                <br />
                2.3. Указывайте тип транспортного средства и марку и модель.
                <br />
                2.4. Указывайте количество посадочных мест. Если это пятиместный автомобиль, то обязательно указать, сколько будет попутчиков сзади.
            </p>

            <h2>3. Рекомендации.</h2>
            <p>
                3.1 с фото автомобиля объявление смотрится лучше. «Иномарка» — не марка. «Шевроле» — не марка. «Шевроле Лачетти» — марка.
                <br />
                3.2 указывайте по возможности маршруты движения (начальная, конечная и промежуточные точки), чтобы к общему удобству согласовать места встречи и места высадки;
                <br />
                3.3  внимательно читайте даты и направления.
                <br />
                3.4  оговаривайте условия заранее: когда платить, остановки, что можно, что нельзя делать в машине, будет ли довоз до подъезда и его условия и т.п.;
                <br />
                3.5 цены «стандарт», «автобусная», «договорная» не существует! Потрудитесь озвучивать;
                <br />
                3.6  представляйтесь при звонке. Нужно это не только по правилам хорошего тона, но и для последующей идентификации звонящего;
                <br />
                3.7 созванивайтесь для уточнения времени встречи и для подтверждения намерений за несколько часов, с тем, чтобы был всегда запасной вариант.
            </p>
        </div>
        <div class="col-md-4 col-sm-4">
        </div>
    </div>
</div>

views/site/safety.php
<?php

/* @var \yii\web\View $this */

$title = 'Техника безопасности при выборе попутчика';
$this->title = $title . ' - ' . Yii::$app->name;
$this->registerMetaTag(['name' => 'description',
    'content' => 'Техника безопастности при поездке попутчиком с незнакомыми людьми. Пожалуйста придерживайтесь этих правил.']);
?>
<div class="row">
    <div class="col-md-8 col-sm-8">
        <h1><?= $title; ?></h1>
        <p>
            Для того, чтобы сделать Вашу совместную поездку максимально безопасной, мы хотели бы порекомендовать несколько довольно простых правил «Техники безопасности», рассказать о реализованных на нашем сайте возможностях для их выполнения.
        </p>
        <h2>Основная идея обеспечения безопасности состоит в следующем: </h2>
        Ваша совместная поездка должна быть максимально публична. На нашем сайте, по возможности, должно остаться максимум информации о том, когда и с кем Вы отправитесь в путь. Это не значит, что все детали будут доступны всем желающим, но, при необходимости, информация будет беспрепятственно передана правоохранительным органам. Согласитесь, что такая перспектива совсем не привлекательна для потенциальных злоумышленников.<br/><br/>
        <h2>Для того, чтобы максимально обезопасить себя, следуйте следующим правилам:</h2>
        Выбирайте для поездки попутчиков с максимально полной указанной информацией (привязка к акаунту соц-сети, подтверждение email-адреса, указание номера мобильного, указание информации об автомобиле). Данная информация надежно хранится в нашей базе данных даже в случае ее дальнейшего изменения попутчиком;<br/><br/>
        Когда Вы нашли на нашем сайте попутчика и приняли решение о совместной поездке, откликнитесь на поездку прямо на сайте.<br/>
        Если Вас нашли по заявке (объявлению) на сайте, выясните максимум информации о Вашем будущем попутчике. <br/>
        Не назначайте встречу с попутчиком в безлюдных местах;<br/><br/>
        При встрече с попутчиком проверьте достоверность имеющейся в Вашем распоряжении информации: внешность (по фото на сайте), фамилия, имя, модель, цвет и номер автомобиля и проч. В случае несовпадения информации откажитесь от совместной поездки.<br/><br/>
        <h3>Желаем Вам счастливого и безопасного пути! </h3>
    </div>
    <div class="col-md-4 col-sm-4">

    </div>
</div>