controllers/AutoController.php
<?php

namespace app\controllers;


use app\companion\model\Car;
use app\models\CarMark;
use app\models\CarModel;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UploadedFile;

class AutoController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                    'models' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index', [

        ]);
    }

    /**
     * @return string
     */
    public function actionCreate()
    {
        $model = new Car();

        if ($model->load(Yii::$app->request->post())) {
            $model->manufacturer = CarMark::findOne($model->mark_id)->name;
            $model->model = CarModel::findOne($model->model_id)->name;
            $model->user_id = Yii::$app->getUser()->getId();
            $file = UploadedFile::getInstance($model, 'avatar');
            $dir = Yii::getAlias('@webroot/img/car/');
            if (!is_dir($dir)) {
                mkdir($dir);
            }
            if ($file) {
                if (is_file($dir . $model->avatar)) {
                    unlink($dir . $model->avatar);
                }
                $fname = uniqid("", true) . '.' . $file->extension;
                $model->avatar = $fname;
                $file->saveAs($dir . $fname);
            }
            if ($model->save()) {
                return $this->redirect('/profile/view');
            }
        }

        return $this->render('form', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findUserModel($id);
        $avatar = $model->avatar;
        if ($model->load(Yii::$app->request->post())) {
            $file = UploadedFile::getInstance($model, 'avatar');
            $dir = Yii::getAlias('@webroot/img/car/');
            if (!is_dir($dir)) {
                mkdir($dir);
            }
            if ($file) {
                if (is_file($dir . $model->avatar)) {
                    unlink($dir . $model->avatar);
                }
                $fname = uniqid("", true) . '.' . $file->extension;
                $model->avatar = $fname;
                $file->saveAs($dir . $fname);
            } else {
                $model->avatar = $avatar;
            }
            if ($model->save()) {
                return $this->redirect('/profile/view');
            }
        }

        return $this->render('form', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {

        $model = $this->findModel($id);

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionDelete($id)
    {
        $model = $this->findUserModel($id);
        $model->status = Car::STATUS_DELETED;
        $model->save();

        return $this->redirect('/profile/view');
    }

    public function actionModels()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $id = Yii::$app->request->post('id');
        if (!$id) {
            return [];
        }

        return CarModel::find()->select(['id', 'name'])->where(['mark_id' => $id])->orderBy(['name' => SORT_ASC])->asArray()->all();
    }

    /**
     * @param $id
     * @return \app\companion\model\Car
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        $model = Car::find()->with(['user'])->where(['id' => $id, 'status' => Car::STATUS_ACTIVE])->one();

        if ($model === null) {
            throw new NotFoundHttpException();
        }

        return $model;
    }

    /**
     * @param $id
     * @return \app\companion\model\Car
     * @throws NotFoundHttpException
     */
    protected function findUserModel($id)
    {
        $model = Car::find()->where(['id' => $id, 'user_id' => Yii::$app->user->id, 'status' => Car::STATUS_ACTIVE])->one();

        if ($model === null) {
            throw new NotFoundHttpException();
        }

        return $model;
    }
}

views/auto/form.php
<?php

use app\companion\model\Car;
use app\models\CarMark;
use app\models\CarModel;
use yii\widgets\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model \app\companion\model\Car */

$this->title = $model->isNewRecord ? 'Добавление автомобиля' : 'Редактирование автомобиля';

$this->params['breadcrumbs'][] = [
    'label' => 'Автомобили',
    'url' => ['/auto/index'],
];

$this->params['breadcrumbs'][] = [
    'label' => $model->getTitle(),
    'url' => ['/auto/view', 'id' => $model->id],
];

$this->params['breadcrumbs'][] = 'Редактирование';


?>

<div class="auto-form">

    <h1><?= Html::encode($this->title); ?></h1>
    <?php $form = ActiveForm::begin([]); ?>
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <?= $form->field($model, 'mark_id')->dropDownList(CarMark::getDropdownList(), [
                        'class' => 'form-control select2',
                        'id' => 'car-mark',
                        'prompt' => '- Выбрать -',
                        'disabled' => $model->isNewRecord ? false : 'disabled'
                    ]); ?>

                    <?= $form->field($model, 'model_id')->dropDownList(CarModel::getDropdownList($model->mark_id), [
                        'id' => 'car-model',
                        'prompt' => '- Выбрать -',
                        'disabled' => $model->isNewRecord ? false : 'disabled'
                    ]); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <?= $form->field($model, 'year')->dropDownList(Car::getYears(), [
                        'class' => 'form-control select2',
                        'prompt' => '- Выбрать -',
                        'disabled' => $model->isNewRecord ? false : 'disabled'
                    ]); ?>
                </div>
                <div class="col-md-4 col-sm-4">
                    <?= $form->field($model, 'state_number')->textInput([
                        'disabled' => $model->isNewRecord || !$model->state_number ? false : 'disabled'
                    ]) ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'description')->textarea(); ?>
                </div>
            </div>


        </div>

        <div class="col-md-6 col-sm-6">
            <label class="progress_load_form_photo_upload">
                <?= Html::img($model->avatar ? '/img/car/' . $model->avatar : '/img/thumbs/no_photo_auto.png', [
                    'class' => 'img-responsive car-img-trip',
                    'style' => 'max-width:100%',
                    'alt' => $userName . ($town ? ' ' . Html::encode($town->name) : ''),
                ]); ?>

                <?= $form->field($model, 'avatar')->fileInput(['class' => 'avatar_img'])->label(false) ?>
                <p class="small text-muted text-center">Кликните на фото для загрузки новой фотографии вашего
                    автомобиля</p>

            </label>
            <div class="form-group">
                <?= Html::submitButton('Сохранить', ['class' => 'btn btn-lg btn-primary']) ?>
            </div>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/auto/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Автомобили наших пользователей - автопарк';
$this->registerMetaTag(['name' => 'description',
    'content' => 'Автопарк нашего проекта. Тут мы покажем вам немног статистики об автомобилях наших пользователеей']);
?>

<div class="auto-index">
    <h1><?= $this->title; ?></h1>
</div>

views/auto/view.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model \app\companion\model\Car */

$this->title = 'Автомобиль ' . $model->getTitle();

$this->registerMetaTag(['name' => 'description',
    'content' => $model->getContent() . '. Владелец автомобиля ' . $model->user->name]);

$this->params['breadcrumbs'][] = [
    'label' => 'Автомобили',
    'url' => ['/auto/index'],
];

$this->params['breadcrumbs'][] = $this->title;

$town = $model->user->town;
?>

<div class="auto-view">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <h1>
                <?= Html::encode($this->title); ?>
                <?php
                if ($model->name) {
                    ?>
                    <span class="car-nickname"><?= $model->name ?></span>
                    <?php
                }
                ?>
            </h1>
        </div>
        <div class="col-md-6 cols-sm-6">

            <h2>
                Владелец: <?= Html::a(Html::encode($model->user->name), ['/profile/view', 'id' => $model->user->id]); ?></h2>
            <?= Html::a(
                Html::img($model->user->avatar ? '/img/profile/' . $model->user->avatar : '/img/thumbs/user150.jpg', [
                    'class' => '',
                    'alt' => Html::encode($model->user ? $model->user->name : 'unknown'),
                ]), ['/profile/view', 'id' => $model->user->id]
            ); ?>

            <h2>Описание машины</h2>
            <div class="lead">
                <?= 'Год выпуска: ' . $model->year . '<br/>'; ?>
                <?= 'Расход топлива: ' . $model->consumption . 'л. на 100км.<br/>'; ?>
                <?= 'Регистрационный номер авто: ' . $model->state_number . '<br/>'; ?>
            </div>
            <?php if ($model->description) { ?>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <?= $model->description; ?>
                    </div>
                </div>
            <?php } ?>
            <div>
                <?= \app\widgets\TripHistory::widget([
                    'userId' => $model->user_id,
                ]); ?>
            </div>

        </div>
        <div class="col-md-6 cols-sm-6">
            <h2>Фото автомобиля</h2>
            <?= Html::img($model->avatar ? '/img/car/' . $model->avatar : '/img/thumbs/no_photo_auto.png', [
                'class' => 'img-responsive car-img-trip',
                'alt' => Html::encode($model->name ? $model->name : 'unknown'),
            ]);
            ?>
        </div>
    </div>
</div>